More documentation
ranking-agent/strider pull request #203
Opened 2021-06-04 18:52 UTC by alongreyber

Added high level documentation overviews for execution and planning. These are good for onboarding onto the project. Couldn't quite finish the planning documentation but got pretty close to done.

2021-10-30 08:00 UTC, davefol requested changes

2021-10-30 08:00 UTC, davefol commented on docs/PLANNING_OVERVIEW.md
> +TODO finish
What else needs to be said here?

2021-10-30 20:59 UTC, alongreyber commented on docs/COMPONENTS.md
> +* `traversal.py` **probably obsolete**
I *think* this actually does something because get_traversals will raise NoAnswersError if it can't find a traversal.

2021-10-30 21:05 UTC, alongreyber commented
This PR looks good except that the `docs/PLANNING_OVERVIEW.md` document is very out of date. I don't really have a good grasp on how the new query planning works. @uhbrar would you be able to update that document? Patrick wrote the docs/QUERY_PLANNING.md document but that isn't really an overview of how it works–it's specifically focused on some statistical optimization stuff.  I think that a planning overview for people new to the code would be helpful to have.

If you also don't know how it works I can dive in and learn about it but I thought I would ask.

2021-10-30 21:06 UTC, alongreyber commented
@davefol I made a milestone for cleaning up dead code so feel free to create issues and link them to it

2021-10-31 00:50 UTC, davefol commented
> This PR looks good except that the `docs/PLANNING_OVERVIEW.md` document is very out of date. I don't really have a good grasp on how the new query planning works. @uhbrar would you be able to update that document? Patrick wrote the docs/QUERY_PLANNING.md document but that isn't really an overview of how it works–it's specifically focused on some statistical optimization stuff. I think that a planning overview for people new to the code would be helpful to have.
> 
> If you also don't know how it works I can dive in and learn about it but I thought I would ask.

perfect is the enemy of good yada yada. I'll make an issue for updaating PLANNING_OVERVIEW.md and tentatively assign @uhbrar to it. I don't want it to block this PR because this is a lot of really good stuff.

2021-11-01 13:11 UTC, kennethmorton commented
I think I might have the clearest (remaining) picture of the query planning algorithm. I'll put this on my list for documentation.

From my current understanding the algorithm we have is pretty solid, and shouldn't need to be overhauled for a while, but we might want to add a few bells and whistles. However those bells and whistles don't offer as much as optimizations elsewhere right now.

2021-11-01 17:17 UTC, davefol commented
I'll add @kennethmorton to the assigned members for issue #321

2021-11-02 12:42 UTC, uhbrar commented
I'll take a look at it as well, although I don't actually know how it works precisely, except for some parts that Patrick shared with me before he left. That being said, besides Kenny, I might have the best chance of getting it fully figured out, and it'll be a good opportunity to look through the code and learn about it for me anyway.

2021-11-02 13:38 UTC, davefol approved these changes

2021-11-02 14:46 UTC, merged