Overhaul
ranking-agent/strider pull request #250
Opened 2021-08-15 01:37 UTC by patrickkwang

Changes:
* Remove a bunch of old, unused stuff
* Refactor things for clarity
* Fix a few bugs
* Speed things up - including dumbing down merging, for now
* Fully parallelize qgraph traversal
  All prioritization and throttling is now done on a per-KP basis by trapi-throttle.

2021-08-16 17:51 UTC, cbizon commented on strider/compatibility.py
> +                response = await client.post(
Are these indents intended?

2021-08-16 18:02 UTC, patrickkwang commented on strider/compatibility.py
> +                response = await client.post(
Yes. This was improperly indented.

2021-08-17 15:39 UTC, uhbrar requested changes
Getting an error message when running tests locally:

`ImportError while importing test module '/app/tests/test_query.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_query.py:10: in <module>
    from strider.server import APP, lookup
strider/server.py:23: in <module>
    from .fetcher import Binder
strider/fetcher.py:21: in <module>
    import aiostream
E   ModuleNotFoundError: No module named 'aiostream'
_____________________ ERROR collecting tests/test_server.py ______________________
ImportError while importing test module '/app/tests/test_server.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_server.py:19: in <module>
    from strider.server import APP
strider/server.py:23: in <module>
    from .fetcher import Binder
strider/fetcher.py:21: in <module>
    import aiostream
E   ModuleNotFoundError: No module named 'aiostream'`

I think references to all of the deleted files haven't been fully removed, so we should probably do that before merging.

2021-08-17 15:43 UTC, patrickkwang commented
Whoops, I will add aiostream to the requirements. Also, it seems that our automated tests are not failing properly.

2021-08-17 15:46 UTC, uhbrar commented
Yeah, I'm not sure why the Github automated tests didn't catch that. Seems like it shouldn't be saying that all checks pass. Also, it seems like Strider takes much longer to build locally now? I don't know whether that is an issue or expected behavior, just something I noticed.

2021-08-17 15:51 UTC, uhbrar commented
Well, luckily, Github is reporting the same thing as I am this time. I have one test failing locally still. "test_self_edge" in test_server.py is failing.

2021-08-17 18:35 UTC, uhbrar approved these changes

2021-08-17 19:09 UTC, merged