Fix independent results bug
ranking-agent/strider pull request #357
Opened 2022-02-28 17:32 UTC by adamviola

Fixes a bug in `fetcher.py` that caused unnecessary nodes to appear in kgraphs provided by `lookup()`. The fix helps merge time.

The fetcher was unintentionally adding nodes and edges to the same intermediate kgraph used across multiple results, causing the size of the kgraph to grow with each subsequent result. We're now deepcopying the initial intermediate kgraph for separate use in each result.

2022-02-28 17:41 UTC, uhbrar requested changes
Also, some tests are failing and some reformatting is necessary. We should make sure all tests pass before we merge these changes.

2022-02-28 17:41 UTC, uhbrar commented on tests/test_server.py
> +async def test_yield_indepedent_results(client):
Can you fix the typo in this line?

2022-02-28 17:43 UTC, uhbrar requested changes

2022-02-28 17:43 UTC, uhbrar commented on tests/test_server.py
> +    breakpoint()
This breakpoint should be removed

2022-02-28 18:51 UTC, kennethmorton approved these changes

2022-03-02 16:20 UTC, uhbrar requested changes
Once we bring this branch up to date, it should be ready to merge in.

2022-03-02 17:10 UTC, uhbrar approved these changes

2022-03-02 17:10 UTC, merged