Category Normalizer Mismatch
ranking-agent/strider pull request #93
Opened 2021-02-10 20:59 UTC by alongreyber

Fixed #62 where the category given does not match the one that is in the normalizer. The fix involves passing the expanded query graph into StriderWorker and then using that for partial results.

2021-02-10 21:09 UTC, patrickkwang reviewed
What if we move the qgraph expansion out of `generate_plans()`? It seems to me that we can basically do it as soon as we receive the qgraph, and throw away the original. This isn't really like an intermediate artifact, it's just how we're interpreting the qgraph. Would that cause problems?

2021-02-10 21:12 UTC, alongreyber commented
I'm not sure if it will cause problems, but I will give it a try. It would make things a bit cleaner.

2021-02-11 01:29 UTC, patrickkwang requested changes
I like this organization much better! Minor fixes.

2021-02-11 01:29 UTC, patrickkwang commented on strider/server.py
> +    plans, _ = await generate_plans(query_graph)
I suspect this is broken. We should write tests for the actual endpoints using FastAPI's TestClient.

2021-02-11 01:29 UTC, patrickkwang commented on strider/query_planner.py
> +) -> (list[dict[Step, list]], dict[str, dict]):
This output signature needs to revert.

2021-02-11 01:29 UTC, patrickkwang commented on tests/server/test_server.py
> +
Extra newline?

2021-02-11 14:37 UTC, patrickkwang approved these changes

2021-02-11 14:39 UTC, merged